# Generated by Django 4.1.2 on 2022-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsectBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('home_country', models.CharField(max_length=30)),
                ('updated', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.BooleanField(default=True)),
                ('end_product', models.BooleanField(default=True)),
                ('primary_focus', models.CharField(max_length=25)),
                ('secondary_focus', models.CharField(max_length=25)),
                ('date_began', models.CharField(max_length=30)),
                ('mailing_address', models.CharField(max_length=60)),
                ('street_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('species', models.ManyToManyField(to='app.species')),
            ],
        ),
    ]
