# Generated by Django 3.2.15 on 2022-10-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_insectbusiness_parent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='active',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='end_product',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='farm',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='updated',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='primary_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_focus', to='app.focus'),
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='secondary_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_focus', to='app.focus'),
        ),
    ]
