# Generated by Django 3.2.15 on 2022-10-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221023_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='insectbusiness',
            name='home_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_focus', to='app.homecountry'),
        ),
    ]
